theme = "identity"
disableKinds = ['taxonomy', 'term']
copyright = "2023 プロフィール.com"

baseURL = "https://xn--dck5ef6fh6g.com/kurage/"
title = "Kurage | プロフィール.com"

[params]
author = "Kurage"
icon = "kurage"
description = "🪼"

[[params.social]]
name = "Home page"
icon = "solid fa-globe"
url = "https://kurage.jp"

[[params.social]]
name = "Bluesky"
icon = "solid fa-at"
url = "https://bsky.app/profile/kurage.jp"
